# Generated by Django 5.2.14 on 2026-05-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('cost_index', models.DecimalField(decimal_places=1, default=5.0, max_digits=4)),
                ('popularity', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('tour', 'Tours & Sightseeing'), ('adventure', 'Adventure'), ('culture', 'Culture & Arts'), ('nature', 'Nature & Parks'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife')], default='tour', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_hrs', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.TextField(blank=True, default='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cities.city')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['category', 'name'],
            },
        ),
    ]
